### ISSUE TITLE
Support codelists in subfield schedules

### ISSUE THREAD

**Issue by nichtich** [gbv/avram#6]
For instance [MARC21 720 - Added Entry-Uncontrolled Name](https://www.loc.gov/marc/bibliographic/bd720.html) has subfield `$4` with value from the [MARC Code List for Relators](http://id.loc.gov/vocabulary/relators):

~~~json
{
  "4": { 
    "label": "Relationship",
    "codes": "http://id.loc.gov/vocabulary/relators"
  }
}
~~~

**Note:** In this particular example the subfield may also be an URI alternative to a code, how to express this in Avram?

~~~json
{
  "4": { 
    "label": "Relationship",
    "anyOf": [
      { "codes": "http://id.loc.gov/vocabulary/relators" },
      { "$ref": "#/definitions/uri" }
    ]
  }
}
~~~

**Comment by cKlee** [comment]
Question: Is it applicable to use more than one list of codes for MARC 720? I guess in your example `http://id.loc.gov/vocabulary/relators` is different from `#/definitions/uri`. Otherwise I don't see the point to allow alternative URIs of the same code list.

Makes more sense for me to take it to the Avram schema:

```json
    "codedvalue": {
        "type": "object",
        "properties": {
            "codes": {
                "oneOf": [
                    {
                        "$ref": "#/definitions/codelist"
                    },
                    {
                        "$ref": "#/definitions/url"
                    }
                ]
            }
        }
    },
```

And if the URI `http://id.loc.gov/vocabulary/relators` SHOULD be known, why not document in the schema?

```json
    "codedvalue": {
        "type": "object",
        "properties": {
            "codes": {
                "oneOf": [
                    {
                        "$ref": "#/definitions/codelist"
                    },
                    {
                        "$ref": "#/definitions/known-uri"
                    }
                ]
            }
        }
    },
    "known-uri": {
        "type": "string",
        "format": "uri",
        "enum": [
            "http://id.loc.gov/vocabulary/relators"
        ]
    }
```

**Comment by nichtich** [comment]
[MARC 21 bibliographic field 720](https://www.loc.gov/marc/bibliographic/bd720.html) defines:

> $4 - **Relationship**: Code or URI that specifies the relationship from the entity described in the record to the entity referenced in the field. More than one relationship code or URI may be used if the name entity has more than one function. A source of relationship codes is: [MARC Code List for Relators](http://id.loc.gov/vocabulary/relators). The code or URI is given after the name portion in name/title fields.

As I understand this, the value of `$4` can be a code *or* an URI. If it is a code it SHOULD come from the code list <http://id.loc.gov/vocabulary/relators>. Avram should be able to express (with MUST instead of SHOULD):

* references to code lists
  * by their URI
  * defined elsewhere in the schema
* reference to data types (e.g. URI) to avoid repeating `pattern`
   * known data types (which one?)
   * custom data types (is this actually needed?)
* alternatives (such as either code from a codelist or an URI)

This issue was only about references to code lists in the first place, we may better open another issue, no?

**Comment by nichtich** [comment]
Mostly duplicate of #4
